root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/server ./cmd/server/main.go"
bin = "./bin/server"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend"]
delay = 1000
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true