services:
  backend:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: go run github.com/air-verse/air

  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgres
    ports:
      - "5435:5435"
    env_file:
      - .env
    command: -p 5435

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  dbdata:
